modLoader="javafml"
loaderVersion="[36,)"
logoFile="logo.png"
logoBlur=false
issueTrackerURL="https://github.com/Darkhax-Minecraft/Bookshelf/issues"
license="LGPL v2.1"

[[mods]]
modId="bookshelf"
updateJSONURL="https://updates.blamejared.com/get?n=bookshelf&gv=1.16.5"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.bookshelf]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bookshelf]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"