modLoader="javafml"
loaderVersion="[31,)"
logoFile="logo.png"
issueTrackerURL="https://github.com/Darkhax-Minecraft/Bookshelf/issues"

[[mods]]
modId="bookshelf"
updateJSONURL="https://updates.blamejared.com/get?n=bookshelf&gv=1.15.2"
version="${version}"
displayName="${mod_name}"
displayURL="${mod_download}"
credits="${mod_credits}"
authors="${mod_authors}"
description='''
${mod_description}
'''

[[dependencies.bookshelf]]
    modId="forge"
    mandatory=true
    versionRange="[31.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bookshelf]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"